#!/bin/bash -eE

site='http://www.bakabt.com'

if [ ! -e ~/.bxt-session ]; then
	"${0%/*}/bxt-login" "${1}" "${2}"
fi
shift; shift

for user in "${@}"; do
	# <td style="white-space:nowrap;"><a  href="user/141302/Jarudin.html">Jarudin</a>
	curl -b ~/.bxt-session --silent \
		"${site}/users.php?class=-&search=${user}" \
	| grep -io "\"user/[0-9]\+/${user}\.html\"" \
	| sed -re 's#^"user/([0-9]+)/([^.]+)\.html"$#\1 \2#'
done

# EOF
