#!/bin/bash -eE

site='http://www.bakabt.com'

"${0%/*}/bxt-finger" "${@}" \
| while read id login; do
	wget -q --load-cookies ~/.bxt-session -O - "${site}/user/${id}/${login}.html" > /tmp/${login}.html
	joindate=`cat /tmp/${login}.html \
		| grep -A 1 "Join date" \
		| egrep -o '<td>.*</td>' \
		| sed -e "s/<[/]\?\(div\|img src\|li id\|a href\|span\|b\|tr\|td\|a\|li\|div\)[^>]*>//g" \
		| awk '{print $1}'`
	ratio=`cat /tmp/${login}.html \
		| egrep -o "style=\"color:[^>]+>[0-9]+\.[0-9]+</span>.*/smilies/" \
		| head -n1 \
		| sed -re 's#^[^>]*>([0-9]+\.[0-9]+)<.*#\1#'`
	uploaded=`cat /tmp/${login}.html \
		| grep -A 1 "Uploaded" \
		| egrep -o '<td align=\"left">[0-9]+\.[0-9]+\ [^>]+\ -\ \([0-9]+\.[0-9]+\ [^>]+\)</td>' \
		| head -n1 \
		| sed -e "s/<[/]\?\(span\|b\|tr\|td\)[^>]*>//g"`
	downloaded=`cat /tmp/${login}.html \
		| grep -A 1 "Downloaded" \
		| egrep -o '<td align=\"left">[0-9]+\.[0-9]+\ [^>]+\ -\ \([0-9]+\.[0-9]+\ [^>]+\)</td>' \
		| head -n1 \
		| sed -e "s/<[/]\?\(span\|b\|tr\|td\)[^>]*>//g"`
	freeleech=`cat /tmp/${login}.html \
		| grep -A 1 "Freeleech" \
		| egrep -o '<td>[0-9]+\.[0-9]+\ .*</td>' \
		| head -n1 \
		| sed -e "s/<[/]\?\(div\|img src\|li id\|a href\|span\|b\|tr\|td\|a\|li\|div\)[^>]*>//g" \
		| awk '{print $1" "$2}'`
	bonuspoints=`cat /tmp/${login}.html \
		| grep -A 1 "Bonus Points" \
		| egrep -o '<td>[0-9]+\ .*</td>' \
		| head -n1 \
		| sed -e "s/<[/]\?\(a href\|span\|b\|tr\|td\|a\)[^>]*>//g" \
		| awk '{print $1}'`
	bonus=`cat /tmp/${login}.html \
		| grep -A 1 "Bonus" \
		| egrep -o '<td>[0-9]+\.[0-9]+\ [^>]+</td>' \
		| head -n1 \
		| sed -e "s/<[/]\?\(span\|b\|tr\|td\)[^>]*>//g"`
	donate=`cat /tmp/${login}.html \
		| grep -A 1 "Donate" \
		| egrep -o '<td>[0-9]+\.[0-9]+\ [^>]+</td>' \
		| head -n1 \
		| sed -e "s/<[/]\?\(span\|b\|tr\|td\)[^>]*>//g"`
	seeding=`cat /tmp/${login}.html \
		| grep -A 1 "seeding_tab" \
		| head -n1 \
		| sed -e "s/<[/]\?\(img src\|li id\|a href\|span\|b\|tr\|td\|a\|li\)[^>]*>//g" \
		| sed -e 's/^[ \t]*//'`
	leeching=`cat /tmp/${login}.html \
		| grep -A 1 "leeching_tab" \
		| head -n1 \
		| sed -e "s/<[/]\?\(img src\|li id\|a href\|span\|b\|tr\|td\|a\|li\)[^>]*>//g" \
		| sed -e 's/^[ \t]*//'`
	seeded=`cat /tmp/${login}.html \
		| grep -A 1 "seeded_tab" \
		| head -n1 \
		| sed -e "s/<[/]\?\(img src\|li id\|a href\|span\|b\|tr\|td\|a\|li\)[^>]*>//g" \
		| sed -e 's/^[ \t]*//'`
	leeched=`cat /tmp/${login}.html \
		| grep -A 1 "leeched_tab" \
		| head -n1 \
		| sed -e "s/<[/]\?\(img src\|li id\|a href\|span\|b\|tr\|td\|a\|li\)[^>]*>//g" \
		| sed -e 's/^[ \t]*//'`
	echo -en "User: ${login} Join Date: ${joindate} Ratio: ${ratio} Uploaded: ${uploaded} Downloaded: ${downloaded} Free Leech: ${freeleech} Bonus Upload: ${bonus} Donate Upload: ${donate} Bonus points: (${bonuspoints}) ${seeding} ${leeching} ${seeded} ${leeched}\n"
if [ -e /tmp/${login}.html ]; then
	rm /tmp/${login}.html
fi
done

# EOF
